name: cocdaily_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  build_runner: ^2.1.7
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  vexana: ^2.7.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
  #   - images/a_dot_ham.jpeg
