name: cocdaily_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  bloc: ^8.0.3
  build_runner: ^2.1.7
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.3.9
  firebase_auth_oauth: ^1.2.0
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  formz: ^0.4.1
  freezed_annotation: any
  google_fonts: ^2.3.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  lottie: ^1.2.2
  share: ^2.0.4
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: any

flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/json/
  #   - images/a_dot_ham.jpeg
